
import { DegreeProject } from "./types";

export const MOCK_PROJECTS: DegreeProject[] = [
  {
    id: "1",
    title: "Implementación de IA en la Optimización de Rutas Urbanas",
    studentId: "user-1",
    advisorIds: ["advisor-1"],
    facultad: "Ingeniería",
    programa: "Tecnología Naval",
    curso: "2026-I",
    researchGroup: "GIMA",
    researchArea: "Logística",
    researchLine: "Navegación",
    researchSubLine: "Automatización",
    proponent1Name: "Juan Pérez",
    proponent1Id: "10001",
    proponent1Email: "juan@ensub.edu.co",
    proponent1Phone: "3001234567",
    proponent2Name: "",
    proponent2Id: "",
    proponent2Email: "",
    proponent2Phone: "",
    proposedDirectorName: "Dr. Roberto Gómez",
    directorSignature: "",
    evaluator1Name: "",
    evaluator2Name: "",
    deliveryDay: "15",
    deliveryMonth: "05",
    deliveryYear: "2026",
    generalObjective: "Diseñar un algoritmo de optimización.",
    specificObjectives: ["Objetivo 1", "Objetivo 2"],
    problemStatement: "Congestión marítima.",
    justification: "Mejorar la eficiencia.",
    methodology: "Metodología ágil.",
    scope: "Alcance delimitado.",
    bibliography: "Referencias.",
    resources: "Equipos de cómputo.",
    schedule: "Cronograma de 6 meses.",
    impact: "Impacto positivo.",
    status: "En Curso",
    summary: "Una investigación sobre movilidad urbana inteligente.",
    documents: ["Propuesta_v1.pdf", "Bibliografia.pdf"]
  } as unknown as DegreeProject,
];
