
"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "es" | "en" | "pt" | "fr" | "it" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    dashboard: "Tablero Principal",
    myProjects: "Mis Proyectos",
    feedback: "Retroalimentación",
    reviewProjects: "Revisar Proyectos",
    tutorados: "Mis Tutorados",
    globalProjects: "Proyectos Globales",
    users: "Usuarios del Sistema",
    logout: "Cerrar Sesión",
    academicProcess: "Proceso Académico",
    institutionalProfile: "Perfil Institucional",
    settings: "Configuración",
    loadingApp: "Iniciando Academia...",
    changeLanguage: "Cambiar Idioma",
    selectLanguage: "Selecciona el idioma",
    barranquilla: "BARRANQUILLA-COLOMBIA",
    searchByTitle: "Buscar por título...",
    manage: "Gestionar",
    verify: "Verificar",
    observe: "Observar",
    edit: "Editar",
    status: "Estado",
    progress: "Avance",
    actions: "Acciones",
    lastUpdate: "Última actualización",
    adminTitle: "Administración Institucional",
    adminDesc: "Gestión global de la facultad y estadísticas de grado.",
    totalUsers: "Total Usuarios",
    totalProjects: "Proyectos Totales",
    gradRate: "Tasa de Graduación",
    lastYear: "respecto al año anterior",
    projectsByFaculty: "Proyectos por Especialidad",
    facultyDistribution: "Distribución de tesis de grado registradas este semestre.",
    systemConfig: "Configuración del Sistema",
    frequentTasks: "Accesos directos a tareas administrativas recurrentes.",
    manageRoles: "Gestionar Roles",
    manageRolesDesc: "Configura quién puede revisar y aprobar proyectos.",
    exportReports: "Exportar Reportes",
    exportReportsDesc: "Genera PDFs detallados para rectoría y decanatura.",
    backups: "Copias de Seguridad",
    backupsDesc: "Estado de respaldos del sistema.",
    advisorTitle: "Inteligencia del Asesor",
    advisorDesc: "Supervisión predictiva y gestión de carga académica.",
    assignedProjects: "Tutorados",
    averageProgress: "Progreso Medio",
    toReview: "Por Revisar",
    atRisk: "En Riesgo",
    projectStatusTable: "Estado de Proyectos",
    studentFollowUp: "Seguimiento de avance y alertas tempranas por estudiante.",
    noProjectsAssigned: "No tienes proyectos asignados bajo tu tutela.",
    studentTitle: "Investigación Formativa",
    studentDesc: "Gestión de Proyectos de Grado - ENSUB",
    newProposal: "Nueva Propuesta",
    draftProposals: "Propuestas en Borrador",
    sentProjects: "Proyectos Enviados",
    noSentProjects: "No tienes proyectos enviados",
    noSentProjectsDesc: "Comienza una propuesta para que el comité académico pueda evaluarla.",
    continueDrafting: "Continuar redactando",
    sentAt: "ENVIADO",
    researchLine: "Línea de Investigación",
    confirmDelete: "¿Estás completamente seguro?",
    confirmDeleteDesc: "Esta acción no se puede deshacer. Se eliminará permanentemente el borrador.",
    cancel: "Cancelar",
    deleteDraft: "Eliminar Borrador",
    proposalTitle: "Propuesta de Trabajo de Grado",
    formatoCode: "FORMATO EDUCA-FT-093-JINEN-V03",
    saving: "Guardando...",
    saved: "Guardado",
    pendingChanges: "Cambios pendientes",
    sendProposal: "Enviar Propuesta",
    exitWithoutSaving: "Salir sin Enviar",
    forceSave: "Forzar Guardado",
    fillAllTabs: "Diligencia todas las pestañas antes de enviar",
    tab1: "1. Identificación",
    tab2: "2. El Problema",
    tab3: "3. Objetivos",
    tab4: "4. Metodología y Ref.",
    currentSection: "Sección Actual del Formato",
    projectTitleLabel: "Título del Trabajo de Grado",
    facultad: "Facultad",
    programa: "Programa",
    curso: "Curso",
    resLine: "Línea de Investigación",
    resSubLine: "Sublínea",
    proponent1: "Nombre Proponente 1",
    proponent2: "Nombre Proponente 2",
    idNumber: "T.I. o C.C.",
    email: "Correo Electrónico",
    phone: "Número Celular",
    proposedDirector: "Director Propuesto",
    directorSignature: "Firma Director",
    deliveryDate: "Fecha de Entrega",
    day: "Día",
    month: "Mes",
    year: "Año",
    summaryLabel: "Resumen de la Propuesta",
    problemDesc: "2.1 Descripción del Problema",
    problemForm: "2.2 Formulación del Problema (Pregunta)",
    justification: "2.3 Justificación",
    genObj: "3.1 Objetivo General",
    specObj: "3.2 Objetivos Específicos",
    methodology: "4.1 Diseño Metodológico",
    expectedRes: "4.2 Resultados Esperados e Impacto",
    biblio: "5. Referencias Bibliográficas",
    preferencesTitle: "Preferencias de Usuario",
    preferencesDesc: "Personaliza tu experiencia en la plataforma institucional.",
    interfaceSettings: "Ajustes de Interfaz",
    languageLabel: "Idioma del Sistema",
    languageDescription: "Selecciona el idioma principal para toda la plataforma.",
    accessibility: "Accesibilidad",
    notifications: "Notificaciones",
    savePreferences: "Guardar Preferencias",
    saveSuccess: "Preferencias actualizadas correctamente",
    audit: "Auditoría",
    auditDesc: "Trazabilidad de cambios y acceso de alumnos.",
    auditHistory: "Historial de Actividad",
    action: "Acción",
    timestamp: "Fecha y Hora",
    actor: "Actor",
    viewHistory: "Historial",
    viewStats: "Estadísticas de Trazabilidad",
    totalCycleTime: "Tiempo de Ciclo Total",
    correctionsCount: "Iteraciones de Corrección",
    auditScore: "Puntaje de Auditoría",
    participationChart: "Participación por Actor",
    activityChart: "Distribución de Actividad",
    timeSpent: "Duración en Estado",
    viewProposal: "Ingreso a Propuesta",
    editProposal: "Modificación de Contenido",
    submitProposal: "Envío Formal",
    thesisModule: "Módulo de Tesis",
    thesisPhase: "Fase de Tesis (APA V1)",
    framework: "Marco Referencial",
    resultsDiscussion: "Resultados y Discusión",
    conclusionsRecommendations: "Conclusiones y Rec.",
    annexes: "Anexos",
    thesisBackground: "Antecedentes de Investigación",
    thesisTheoretical: "Marco Teórico",
    thesisConceptual: "Marco Conceptual",
    thesisLegal: "Marco Legal",
    thesisResults: "Resultados de la Investigación",
    thesisDiscussion: "Análisis y Discusión",
    thesisConclusions: "Conclusiones",
    thesisRecommendations: "Recomendaciones",
    thesisAnnexesLabel: "Anexos y Apéndices",
    saveThesis: "Guardar Avance de Tesis",
    undoCorrection: "Anular Corrección",
    askCorrection: "Pedir Corrección",
    approvePhase: "Aprobar Fase (Visto Bueno)",
    printProposal: "Imprimir Propuesta",
    corregir: "Corregir"
  },
  en: {
    dashboard: "Main Dashboard",
    myProjects: "My Projects",
    feedback: "Feedback",
    reviewProjects: "Review Projects",
    tutorados: "My Tutees",
    globalProjects: "Global Projects",
    users: "System Users",
    logout: "Log Out",
    academicProcess: "Academic Process",
    institutionalProfile: "Institutional Profile",
    settings: "Settings",
    loadingApp: "Starting Academia...",
    changeLanguage: "Change Language",
    selectLanguage: "Select language",
    barranquilla: "BARRANQUILLA-COLOMBIA",
    searchByTitle: "Search by title...",
    manage: "Manage",
    verify: "Verify",
    observe: "Observe",
    edit: "Edit",
    status: "Status",
    progress: "Progress",
    actions: "Actions",
    lastUpdate: "Last update",
    adminTitle: "Institutional Administration",
    adminDesc: "Global faculty management and degree statistics.",
    totalUsers: "Total Users",
    totalProjects: "Total Projects",
    gradRate: "Graduation Rate",
    lastYear: "vs last year",
    projectsByFaculty: "Projects by Specialty",
    facultyDistribution: "Distribution of degree theses registered this semester.",
    systemConfig: "System Configuration",
    frequentTasks: "Shortcuts to recurring administrative tasks.",
    manageRoles: "Manage Roles",
    manageRolesDesc: "Configure who can review and approve projects.",
    exportReports: "Export Reports",
    exportReportsDesc: "Generate detailed PDFs for rectory and deanery.",
    backups: "Backups",
    backupsDesc: "System backup status.",
    advisorTitle: "Advisor Intelligence",
    advisorDesc: "Predictive supervision and academic load management.",
    assignedProjects: "Tutees",
    averageProgress: "Average Progress",
    toReview: "To Review",
    atRisk: "At Risk",
    projectStatusTable: "Project Status",
    studentFollowUp: "Progress tracking and early warnings per student.",
    noProjectsAssigned: "You have no projects assigned under your tutelage.",
    studentTitle: "Formative Research",
    studentDesc: "Degree Projects Management - ENSUB",
    newProposal: "New Proposal",
    draftProposals: "Draft Proposals",
    sentProjects: "Sent Projects",
    noSentProjects: "You have no sent projects",
    noSentProjectsDesc: "Start a proposal so the academic committee can evaluate it.",
    continueDrafting: "Continue drafting",
    sentAt: "SENT",
    researchLine: "Research Line",
    confirmDelete: "Are you absolutely sure?",
    confirmDeleteDesc: "This action cannot be undone. The draft will be permanently deleted.",
    cancel: "Cancel",
    deleteDraft: "Delete Draft",
    proposalTitle: "Degree Project Proposal",
    formatoCode: "FORMAT EDUCA-FT-093-JINEN-V03",
    saving: "Saving...",
    saved: "Saved",
    pendingChanges: "Pending changes",
    sendProposal: "Send Proposal",
    exitWithoutSaving: "Exit without Saving",
    forceSave: "Force Save",
    fillAllTabs: "Fill all tabs before sending",
    tab1: "1. Identification",
    tab2: "2. The Problem",
    tab3: "3. Objectives",
    tab4: "4. Methodology & Ref.",
    currentSection: "Current Format Section",
    projectTitleLabel: "Degree Project Title",
    facultad: "Faculty",
    programa: "Program",
    curso: "Course",
    resLine: "Research Line",
    resSubLine: "Research Sub-line",
    proponent1: "Proponent 1 Name",
    proponent2: "Proponent 2 Name",
    idNumber: "ID Number",
    email: "Email",
    phone: "Phone Number",
    proposedDirector: "Proposed Director",
    directorSignature: "Director Signature",
    deliveryDate: "Delivery Date",
    day: "Day",
    month: "Month",
    year: "Year",
    summaryLabel: "Proposal Summary",
    problemDesc: "2.1 Problem Description",
    problemForm: "2.2 Problem Formulation (Question)",
    justification: "2.3 Justification",
    genObj: "3.1 General Objective",
    specObj: "3.2 Specific Objectives",
    methodology: "4.1 Methodological Design",
    expectedRes: "4.2 Expected Results & Impact",
    biblio: "5. Bibliographic References",
    preferencesTitle: "User Preferences",
    preferencesDesc: "Personalize your experience on the institutional platform.",
    interfaceSettings: "Interface Settings",
    languageLabel: "System Language",
    languageDescription: "Select the primary language for the entire platform.",
    accessibility: "Accessibility",
    notifications: "Notifications",
    savePreferences: "Save Preferences",
    saveSuccess: "Preferences updated successfully",
    audit: "Audit",
    auditDesc: "Traceability of changes and student access.",
    auditHistory: "Activity History",
    action: "Action",
    timestamp: "Timestamp",
    actor: "Actor",
    viewHistory: "History",
    viewStats: "Traceability Stats",
    totalCycleTime: "Total Cycle Time",
    correctionsCount: "Correction Iterations",
    auditScore: "Audit Score",
    participationChart: "Actor Participation",
    activityChart: "Activity Distribution",
    timeSpent: "Duration in State",
    viewProposal: "Proposal Access",
    editProposal: "Content Modification",
    submitProposal: "Formal Submission",
    thesisModule: "Thesis Module",
    thesisPhase: "Thesis Phase (APA V1)",
    framework: "Framework",
    resultsDiscussion: "Results & Discussion",
    conclusionsRecommendations: "Conclusions & Rec.",
    annexes: "Annexes",
    thesisBackground: "Research Background",
    thesisTheoretical: "Theoretical Framework",
    thesisConceptual: "Conceptual Framework",
    thesisLegal: "Legal Framework",
    thesisResults: "Research Results",
    thesisDiscussion: "Analysis & Discussion",
    thesisConclusions: "Conclusions",
    thesisRecommendations: "Recommendations",
    thesisAnnexesLabel: "Annexes & Appendices",
    saveThesis: "Save Thesis Progress",
    undoCorrection: "Undo Correction",
    askCorrection: "Ask Correction",
    approvePhase: "Approve Phase",
    printProposal: "Print Proposal",
    corregir: "Correct"
  },
  pt: {
    dashboard: "Painel Principal",
    thesisModule: "Módulo de Tese",
    thesisPhase: "Fase de Tese (APA V1)",
    undoCorrection: "Desfazer Correção"
  },
  fr: {
    dashboard: "Tableau de Bord",
    thesisModule: "Module de Thèse",
    thesisPhase: "Phase de Thèse (APA V1)",
    undoCorrection: "Annuler la Correction"
  },
  it: {
    dashboard: "Cruscotto",
    thesisModule: "Modulo di Tesi",
    thesisPhase: "Phase de Thèse (APA V1)",
    undoCorrection: "Annulla Correzione"
  },
  de: {
    dashboard: "Haupt-Dashboard",
    thesisModule: "Thesis-Modul",
    thesisPhase: "Thesis-Phase (APA V1)",
    undoCorrection: "Korrektur rückgängig machen"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("es");

  useEffect(() => {
    const savedLang = localStorage.getItem("app_lang") as Language;
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("app_lang", lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
